### ISSUE TITLE
Is there no release for macOS?

### ISSUE THREAD

**Issue by dayAndnight2018** [Gramli/Scriper#16]

**Comment by Gramli** [comment]
Good point, I will publish self-contained release, but it will be large on disk.

It will be nice to create installer for macOS, do you know some [NSIS](https://nsis.sourceforge.io/Main_Page) alternative for macOS?

**Comment by Gramli** [comment]
MacOS released [MacOS Release](https://github.com/Gramli/Scriper/releases/download/v1.1/ScriperLinux.7z)
